services:
  - type: web
    name: audio-echo-app
    env: docker
    plan: free
    region: singapore
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    branch: main
    envVars:
      - key: PORT
        value: 8000
